# -*- coding: utf-8 -*-
"""NPK_extractor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k4eEEszeByIFdEFdNr95I66PRh2GVtSa
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import matplotlib.pyplot as plt

# Read the existing data from the CSV file
nph_data = pd.read_csv('NPKph.csv')

District = "Jalgaon"
City = "Baramati"
#(nph_data['District'] == District)
filtered_data = nph_data[ (nph_data['City/Village'] == City)]

# Access the 'Min_x0020_Price' and 'Max_x0020_Price' columns from the filtered data
Ph = filtered_data['Ph'].values
N = filtered_data['N'].values
P = filtered_data['P'].values
K = filtered_data['K'].values
Rf = filtered_data['Rainfall'].values

print(Ph)
print(N)
print(P)
print(K)
print(Rf)

